Repository sonatype-nexus-community/jake, pull requests merged in 2022-01, with the labels that each got.

#85 feat(pre-commit): add pre-commit hooks
  .pre-commit-hooks.yaml
  README.md
Labels: cla:signed

#87 feat: support CycloneDX 1.4
  jake/app.py
  jake/command/__init__.py
  jake/command/iq.py
  jake/command/oss.py
  jake/command/sbom.py
  poetry.lock
  pyproject.toml
  tests/test_jake.py
Labels: enhancement

#92 fix: `bom-ref` will always now be populated for Component and Vulnerability
  jake/command/oss.py
  poetry.lock
  pyproject.toml
Labels: bug, enhancement

#94 fix: corrected data placement for Vulnerabilities returned from OSS Index when generating an SBOM
  jake/command/oss.py
Labels: bug
